name: Publish @gdoor/material

on:
  push:
    branches: [ main ]
    paths: [ 'projects/material/**/*', '.github/workflows/publish-material-lib.yml' ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2.3.2

      - uses: actions/setup-node@v1.4.3
        with:
          node-version: 12
          scope: '@gdoor'
          registry-url: https://registry.npmjs.org/

      - run: npm i -g yarn

      - name: Build
        id: build
        run: |
          yarn install
          cd projects/material
          echo "##[set-output name=version;]$(npm version patch --no-git-tag-version)"
          cd ../..
          yarn ng build material --prod

      - name: Pushes new version
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add projects/material/package.json
          git commit -m "${{ github.repository }}@${{ steps.build.outputs.version }}"
          git push $REMOTE

      - name: Publish to npmjs
        run: |
          cd dist/material
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
