name: Publish sak's GitHub pages

on:
  push:
    branches: [ main ]
    paths: 'projects/sak/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2.3.2

      - uses: actions/setup-node@v1.4.3
        with:
          node-version: 12

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn install
          npm run ng deploy
