name: Publish SAK's GitHub Pages

on:
  push:
    branches: [ main ]
    paths: [ 'projects/sak/**/*', '.github/workflows/publish-ghpages.yml' ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2.3.2

      - uses: actions/setup-node@v1.4.3
        with:
          node-version: 12

      - name: Build site
        id: build
        run: |
          yarn install
          echo "##[set-output name=version;]$(npm version patch --no-git-tag-version)"
          yarn ng build --prod --output-path=docs --base-href=https://gdoor-sistemas.github.io/sak/
          cp docs/index.html docs/404.html
          
      - name: Publish docs to repo
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add docs/*
          git add package.json
          git commit -m "docs: updates github page (${{ steps.build.outputs.version }})"
          git push $REMOTE
